# .github/workflows/dotnet.yml
name: .NET Calculator CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore Dependencies
      run: dotnet restore Calculator.App/Calculator.App.csproj
    
    - name: Build Calculator
      run: dotnet build Calculator.App/Calculator.App.csproj --no-restore --verbosity minimal
    
    - name: Verify Build Output
      run: |
        echo "Build completed successfully!"
        echo "Executable created in: Calculator.App/bin/"