version: '3.8'

services:
  calculator-api:
    image: calculator-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5208:80"
      - "7143:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7143
    volumes:
      - ./Data:/app/Data
